trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: hawaVB

steps:
  - task: TerraformInstaller@1
    displayName: Install Terraform
    inputs:
      terraformVersion: "latest"

  - task: TerraformTaskV4@2
    displayName: Terraform Init
    inputs:
      provider: "azurerm"
      command: "init"
      backendServiceArm: "$(AZDOName)"
      backendAzureRmResourceGroupName: "$(RGName)"
      backendAzureRmStorageAccountName: "$(STGName)"
      backendAzureRmContainerName: "$(ContName)"
      backendAzureRmKey: "$(TFStatefileName)"

  - task: TerraformTaskV4@2
    displayName: Terraform Destroy
    inputs:
      provider: "azurerm"
      command: "destroy"
      commandOptions: "--auto-approve"