trigger:
  branches:
    include:
      - main
  paths:
    include:
      - variables.tf
      - infra.tf

pool:
  vmImage: ubuntu-latest

variables:
  -group: hawaVB

steps:
  - task: TerraformTaskV4@4
    displayName: "Terraform Init"
    inputs:
      provider: "azurerm"
      command: "init"
      backendServiceArm: "$(AZDOName)"
      backendAzureRmResourceGroupName: "$(RGName)"
      backendAzureRmStorageAccountName: "$(STGName)"
      backendAzureRmContainerName: "$(ContName)"
      backendAzureRmKey: "$(TFStatefileName)"

  - task: TerraformTaskV4@4
    displayName: "Terraform Validate"
    inputs:
      provider: "azurerm"
      command: "validate"

  - task: TerraformTaskV4@4
    displayName: "Terraform Plan"
    inputs:
      provider: "azurerm"
      command: "plan"
      environmentServiceNameAzureRM: "$(AZDOName)"

  - task: TerraformTaskV4@4
    displayName: "Terraform Apply"
    condition: succeeded('Terraform Validate')
    inputs:
      provider: "azurerm"
      command: "apply"
      environmentServiceNameAzureRM: "$(AZDOName)"