trigger:
  branches:
    include:
      - main
  paths:
    include:
      - /variables.tf
      - /main.tf

pool:
  vmImage: ubuntu-latest

variables:
  - group: hawaVB

steps:
  - task: TerraformInstaller@1
    displayName: Install Terraform
    inputs:
      terraformVersion: "latest"

  - task: TerraformTaskV4@4
    displayName: Terraform Init
    inputs:
      provider: "azurerm"
      command: "init"
      backendServiceArm: "azdo-tfaz-conn"
      backendAzureRmResourceGroupName: "$(RGName)"
      backendAzureRmStorageAccountName: "$(STGName)"
      backendAzureRmContainerName: "$(ContName)"
      backendAzureRmKey: "$(TFStatefileName)"

  - task: TerraformTaskV4@4
    displayName: Terraform Validate
    inputs:
      provider: "azurerm"
      command: "validate"

  - task: TerraformTaskV4@4
    displayName: Terraform Plan
    inputs:
      provider: "azurerm"
      command: "plan"
      environmentServiceNameAzureRM: "azdo-tfaz-conn"

  - task: TerraformTaskV4@4
    displayName: Terraform Apply
    inputs:
      provider: "azurerm"
      command: "apply"
      environmentServiceNameAzureRM: "azdo-tfaz-conn"